language: python
python:
  - "2.7"
  - "3.4"

install:
  - pip install coverage
  - pip install prettytable
  - pip install PySerial
  - pip install mbed-ls
  - pip install mbed-host-tests
  - pip install junit-xml
  - pip install lockfile
  - pip install colorama

script: python setup.py test

after_success:
  - coverage run setup.py test
  - coverage html
